### ISSUE TITLE
Consider detaching fork

### ISSUE THREAD

**Issue by CoffeeCoder1** [roboblazers7617/2024Robot-Post-Season#3]
Detaching this fork from the upstream repo would make managing branches on this repo easier (comparisons would be within this repo instead of comparing to upstream branches), and would also enable some features on this repository like contribution graphs. This would have to be done through GitHub Support, and a support request for this can be submitted on [this page](https://support.github.com/request/fork).

**Comment by CoffeeCoder1** [comment]
@fodfodfod Can you take a look at this?

**Comment by fodfodfod** [comment]
A request to detach has been made. Once it is approved I will archive the original repo.

**Comment by CoffeeCoder1** [comment]
@fodfodfod The request appears to have been approved, so you should be able to archive the old repo now.
